name: Quay

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"
  workflow_dispatch:

env:
  REGISTRY: quay.io
  OCP_VERSIONS: "4.5 4.6 4.7 4.8 4.9"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Registry login
        run: echo "${{ secrets.QUAY_TOKEN }}" | podman login ${REGISTRY} -u ${{ secrets.QUAY_USER }} --password-stdin

      - name: Build and Push the index image
        run: |
          ORG=${GITHUB_REPOSITORY%/*}
          TAG=$(git tag --points-at HEAD)
          VERSION=${TAG/v/}
          make all ORG=${ORG} VERSION=${VERSION}

      - name: Add component to DCI (distributed-ci.io)
        run: |
          REPO_NAME=${GITHUB_REPOSITORY/*\/}}
          CANONICAL_NAME=
          pip install dciclient
          source <(cat <<EOF
          ${{ secrets.REMOTECI }}
          EOF
          )
          TAG=$(git tag --points-at HEAD)
          NAME="${REPO_NAME}:${TAG}"
          CANONICAL="${CANONICAL_NAME}:${TAG}"
          TYPE="operator-index"
          URL="${REGISTRY}/${GITHUB_REPOSITORY}:${TAG}"
          TEAM_ID=$( dcictl --format json team-list | jq -r '.teams[]|.id' )
          for ocp_version in ${OCP_VERSIONS}; do
            topic_id=$( dcictl --format json topic-list | jq -r '.topics[]| select(.name=="OCP-${ocp_version}")|.id' )
            dcictl component-create \
              --topic-id ${topic_id} \
              --team-id ${TEAM_ID} \
              --name ${NAME} \
              --canonical_project_name ${CANONICAL} \
              --type ${TYPE} \
              --url ${URL}
          done
