name: Publish images and create DCI components

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"
  workflow_dispatch:

env:
  REGISTRY: quay.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and Push the index image
        run: |
          ORG=${GITHUB_REPOSITORY%/*}
          TAG=$(git tag --points-at HEAD)
          VERSION=${TAG/v/}
          make all ORG=${ORG} VERSION=${VERSION}

      - name: Create DCI components
        uses: dci-labs/dci-component@v1
        with:
          dciClientId: ${{ secrets.DCI_CLIENT_ID }}
          dciApiSecret: ${{ secrets.DCI_API_SECRET }}
          dciTopics: '
          OCP-4.9,
          OCP-4.10,
          OCP-4.11,
          OCP-4.12,
          OCP-4.13,
          OCP-4.14,
          '
          componentName: nfv-example-cnf-index
          componentVersion: ${{ github.ref_name }}
          componentData: '{"url":"${{ env.REGISTRY }}/${{ github.repository_owner }}/nfv-example-cnf-catalog"}'
          componentRelease: ga
        id: dci

      - name: Results
        run: |
          echo "## DCI components" >> ${GITHUB_STEP_SUMMARY}
          echo "" >> ${GITHUB_STEP_SUMMARY}
          echo "\`\`\`JSON" >> ${GITHUB_STEP_SUMMARY}
          <<<'${{ steps.dci.outputs.components }}' jq . >> ${GITHUB_STEP_SUMMARY} 
          echo "\`\`\`" >> ${GITHUB_STEP_SUMMARY}
          echo "" >> ${GITHUB_STEP_SUMMARY}
